/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.java;

import gradle.java.infrastructure.interactions.CustomerChoice;
import gradle.java.infrastructure.presentation.CatalogueFormatter;
import gradle.java.infrastructure.presentation.CataloguePresentation;
import gradle.java.infrastructure.repositories.ProductWareHouse;

public class App {

  public static void main(String[] args) {
    ProductWareHouse productWareHouse = new ProductWareHouse();
    CatalogueFormatter catalogueFormatter = new CatalogueFormatter();
    CataloguePresentation cataloguePresentation = new CataloguePresentation(productWareHouse, catalogueFormatter);
    OnlineShop onlineShop = new OnlineShop(cataloguePresentation);
    CustomerChoice customerChoice = new CustomerChoice(cataloguePresentation);
    onlineShop.showProducts();
    customerChoice.productsToChooseExplore();
    customerChoice.decideWhatToDoNext();
  }
}
