/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.java;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertThat(1).isEqualTo(1);
    }
}
